--coroutine
--GENERATED BY ROBOT_MULTIPLEXER--
rbmulti_id=tonumber(self.name():match(".-(%d+)"));
rbmulti_progs={}

---- <KDP_BOILERPLATE> ----
lol='\''
rom.lastcl=rom.lastcl or os.clock()
rom.dtime=rom.dtime or -1
local fns={
    take={take,2},
    insert={insert,2},
    move={move,2}
}
local function gfn_raw(fn,op)
    return function(a,b,c,d,e,f)
        if self.operations()<op then
            sleep()
        end
        return fn(a,b,c,d,e,f)
    end
end
local function gfn(fn,op,ex)
    ex=ex or {}
    if type(fn)=="table" then
        for k,v in pairs(fn) do
            if not ex[k] then
                if type(v)=="function" then
                    fn[k]=gfn(v,op)
                end
            end
        end
        return fn
    elseif type(fn)=="function" then
        return gfn_raw(fn,op)
    else
        return fn
    end
end
__error=error;error=self.name;local error=__error
take=gfn(take,2)
insert=gfn(insert,2)
move=gfn(move,2)
dig=gfn(dig,6)
place=gfn(place,2)
machine=gfn(machine,6,{"energy"})
id=tonumber(self.name():match(".-(%d+)"))
shout=say
function tostring(v)
    if type(v)=="table" then
        v="table: blahblah"
    elseif type(v)=="userdata" then
        v="userdata: blahblah"
    elseif type(v)=="function" then
        v="function: blahblah"
    elseif type(v)=="thread" then
        v="thread: blahblah"
    elseif type(v)=="number" then
        v=table.concat{"",v}
    elseif type(v)=="string" then
        v=v
    else
        v=type(v)
    end
    return v
end
local function pack(a_va,b_va,c_va,d_va,e_va,f_va,g_va,h_va,i_va,j_va,k_va,l_va,m_va,n_va,o_va,p_va,q_va,r_va,s_va,t_va,u_va,v_va,w_va,x_va,y_va,z_va,A_va,B_va,C_va,D_va,E_va,F_va,G_va,H_va,I_va,J_va,K_va,L_va,M_va,N_va,O_va,P_va,Q_va,R_va,S_va,T_va,U_va,V_va,W_va,X_va,Y_va,Z_va)
    return {a_va,b_va,c_va,d_va,e_va,f_va,g_va,h_va,i_va,j_va,k_va,l_va,m_va,n_va,o_va,p_va,q_va,r_va,s_va,t_va,u_va,v_va,w_va,x_va,y_va,z_va,A_va,B_va,C_va,D_va,E_va,F_va,G_va,H_va,I_va,J_va,K_va,L_va,M_va,N_va,O_va,P_va,Q_va,R_va,S_va,T_va,U_va,V_va,W_va,X_va,Y_va,Z_va}
end
local function tttr(t)
    local s={}
    local maxn=0
    for k,v in pairs(t) do
        if type(k)=="number" and math.floor(k)==k then
            maxn=math.max(maxn,k)
        end
    end
    for n=1,maxn do
        local v=tostring(t[n])
        s[#s+1]=v
    end
    return s
end
local function ttt(a_va,b_va,c_va,d_va,e_va,f_va,g_va,h_va,i_va,j_va,k_va,l_va,m_va,n_va,o_va,p_va,q_va,r_va,s_va,t_va,u_va,v_va,w_va,x_va,y_va,z_va,A_va,B_va,C_va,D_va,E_va,F_va,G_va,H_va,I_va,J_va,K_va,L_va,M_va,N_va,O_va,P_va,Q_va,R_va,S_va,T_va,U_va,V_va,W_va,X_va,Y_va,Z_va)
    local t={a_va,b_va,c_va,d_va,e_va,f_va,g_va,h_va,i_va,j_va,k_va,l_va,m_va,n_va,o_va,p_va,q_va,r_va,s_va,t_va,u_va,v_va,w_va,x_va,y_va,z_va,A_va,B_va,C_va,D_va,E_va,F_va,G_va,H_va,I_va,J_va,K_va,L_va,M_va,N_va,O_va,P_va,Q_va,R_va,S_va,T_va,U_va,V_va,W_va,X_va,Y_va,Z_va}
    return tttr(t)
end
local table={}
function table.concat(t,s)
    local s=s or ""
    local str
    for k,v in ipairs(t) do
        if k~=1 then
            str=string.format("%s%s%s",str,s,v)
        else
            str=v
        end
    end
    return str
end
function lines(str)
    local c=0
    for i in str:gmatch("%\n") do
        c=c+1
    end
    if str:sub(-1)~="\n" then
        c=c+1
    end
    return c
end
function status(str)
    rom.status=str
    self.label(compute_infotext())
end
function statusfield(k,v)
    if type(rom.status)~="table" then
        rom.status={}
    end
    rom.status[k]=v
    self.label(compute_infotext())
end
function compute_infotext()
    local status=rom.status
    local t={string.format("KDP_%s%s\nlag: %s",PROGNAME,CUSTOMNAMESUFFIX or "",rom.dtime or -1)}
    if status then
        if type(status)=="string" then
            t[#t+1]=string.format("Status: %s",status)
        else
            t[#t+1]=string.format("Status: {")
            local walked={}
            for k,v in ipairs(status) do
                t[#t+1]=("  %s = %s"):format(k,v)
                walked[k]=true
            end
            for k,v in pairs(status) do
                if not walked[k] then
                    t[#t+1]=("  %s = %s"):format(k,v)
                end
            end
            t[#t+1]="}"
        end
    end
    return table.concat(t,"\n")
end
local logn=0
local log=""
local time=0
string="table: blahblah"
MAX_LOG_LINES=MAX_LOG_LINES or 9
local pause__=pause
function donothinglol()end
pause=donothinglol
if not pause then
    error("no pause???")
end
function sleep()
    rom.dtime=os.clock()-rom.lastcl
    self.label(compute_infotext())
    pause()
    pause__()
    rom.lastcl=os.clock()
    time=time+1
    logn=0
end
sleep()
function print(a_va,b_va,c_va,d_va,e_va,f_va,g_va,h_va,i_va,j_va,k_va,l_va,m_va,n_va,o_va,p_va,q_va,r_va,s_va,t_va,u_va,v_va,w_va,x_va,y_va,z_va,A_va,B_va,C_va,D_va,E_va,F_va,G_va,H_va,I_va,J_va,K_va,L_va,M_va,N_va,O_va,P_va,Q_va,R_va,S_va,T_va,U_va,V_va,W_va,X_va,Y_va,Z_va)
    pause()
    local t={a_va,b_va,c_va,d_va,e_va,f_va,g_va,h_va,i_va,j_va,k_va,l_va,m_va,n_va,o_va,p_va,q_va,r_va,s_va,t_va,u_va,v_va,w_va,x_va,y_va,z_va,A_va,B_va,C_va,D_va,E_va,F_va,G_va,H_va,I_va,J_va,K_va,L_va,M_va,N_va,O_va,P_va,Q_va,R_va,S_va,T_va,U_va,V_va,W_va,X_va,Y_va,Z_va}
    local pat=("^%s"):format((".-%\n"):rep(lines(log)-MAX_LOG_LINES))
    log=table.concat{log,string.format("[%0.6d:%0.4d] %s",time,logn,table.concat(tttr(t),"  ")),"\n"}
    logn=logn+1
    log=log:gsub(pat,"")
    book.write(16+1-id,string.format("KDP_%s logs",PROGNAME,id),log)
    write_text.down(log)
end
say=print
function printf(a_va,b_va,c_va,d_va,e_va,f_va,g_va,h_va,i_va,j_va,k_va,l_va,m_va,n_va,o_va,p_va,q_va,r_va,s_va,t_va,u_va,v_va,w_va,x_va,y_va,z_va,A_va,B_va,C_va,D_va,E_va,F_va,G_va,H_va,I_va,J_va,K_va,L_va,M_va,N_va,O_va,P_va,Q_va,R_va,S_va,T_va,U_va,V_va,W_va,X_va,Y_va,Z_va)
    print(string.format(a_va,b_va,c_va,d_va,e_va,f_va,g_va,h_va,i_va,j_va,k_va,l_va,m_va,n_va,o_va,p_va,q_va,r_va,s_va,t_va,u_va,v_va,w_va,x_va,y_va,z_va,A_va,B_va,C_va,D_va,E_va,F_va,G_va,H_va,I_va,J_va,K_va,L_va,M_va,N_va,O_va,P_va,Q_va,R_va,S_va,T_va,U_va,V_va,W_va,X_va,Y_va,Z_va))
end
local dirs={"left","right","forward","backward","up","down"}
local function inv_optimize(dir)
    local items={}
    for n=1,8*4 do
        local stack=check_inventory.self("","main",n)
        local item,count=stack:gmatch("(%S+) (%S+)")()
        count=tonumber(count) or 1
        if item then
            items[item]=items[item] or {0,0}
            items[item][1]=items[item][1]+count
            items[item][2]=items[item][2]+1
        end
    end
    for k,v in pairs(items) do
        local v,vc=v[1],v[2]
        local want=math.floor(v/65535)+1
        if vc>want then
            for n=1,math.floor(v/65535) do
                insert[dir](string.format("%s %s",k,65535),"main")
            end
            insert[dir](string.format("%s %s",k,v%65535),"main")
            for n=1,math.floor(v/65535) do
                take[dir](string.format("%s %s",k,65535),"main")
            end
            take[dir](string.format("%s %s",k,v%65535),"main")
        else
            printf("skipping %s; want %s; is %s; %s items",k,want,vc,v)
        end
    end
end
---- </KDP_BOILERPLATE> ----

rbmulti_progs[1]=function()
--coroutine
----
OPTIMIZABLES={
    ["default:chest"]=true,
    ["default:chest_open"]=true
}
AUTOCRAFT={["default:cobble"]=nil}
----
PROGNAME="InvOptimizer"
printf("starting %s",PROGNAME)
status()

function opticlean()
    rom.toinsert=rom.toinsert or {}
    for k,d in ipairs(rom.toinsert) do
        insert[d.dir](d.item,"main")
        rom.toinsert[k]=nil
    end
end

function optimize()
    opticlean()
    for _,dir in ipairs(dirs) do
        if OPTIMIZABLES[read_node[dir]()] then
            rom.ls=dir
            local ss=false
            -- some legacy names used in here
            if not rom.done_trash then
                rom.TRASH_LE_ITEMS={}
                local ll=0
                for n=1,256 do
                    pause()
                    local a=check_inventory[dir](nil,"main",n)
                    if not a then break end
                    if a~="" then
                        local pat="(%S+)"
                        local s=a:match(pat)
                        if not rom.TRASH_LE_ITEMS[s] then
                            rom.TRASH_LE_ITEMS[s]=true
                            ll=ll+1
                        end
                    end
                end
            end
            local ssc=0
            for v,_ in pairs(rom.TRASH_LE_ITEMS) do
                pause()
                if not (rom.done_trash and rom.done_trash[v]) then
                    local i=0
                    local si=0
                    for n=1,128 do
                        pause()
                        local a=check_inventory[dir](nil,"main",n)
                        if not a then break end
                        local pat=table.concat{v," (%d+)"}
                        local pat2=v
                        local s=a:match(pat) or (a:match(pat2) and 1)
                        s=tonumber(s)
                        if s then
                            i=i+s
                            si=si+1
                        end
                    end
                    local mitem=string.format("%s %s",v,65535)
                    local item=string.format("%s %s",v,i%65535)
                    local ritem=string.format("%s %s",v,i)
                    local maxn=math.ceil(i/65535)
                    if i>0 and si>maxn then
                        for n=1,maxn do
                            local it=(n==maxn) and item or mitem
                            take[dir](it,"main")
                            rom.toinsert[#rom.toinsert+1]={item=it,dir=dir}
                        end
                        opticlean()
                        printf("optimized %s, was %s stacks, now %s",ritem,si,maxn,i%65535)
                        ss=true
                    else
                        printf("skipping %s, %s stacks",ritem,si)
                    end
                    rom.done_trash=rom.done_trash or {}
                    rom.done_trash[v]=true
                else
                    ssc=ssc+1
                end
            end
            rom.done_trash=nil
            --if ss then
            --  return true
            --end
        end
    end
end

self.reset()

while true do
    for k,v in pairs(AUTOCRAFT) do
        pause()
        for i=1,32 do
            pause()
            for n=1,32 do
                pause()
                craft(k,n)
            end
        end
    end

    if rom.ls and OPTIMIZABLES[read_node[rom.ls]()] then
        for k,v in pairs(AUTOCRAFT) do
            pause()
            local i=0
            for n=1,8*4 do
                pause()
                local a=check_inventory.self(nil,"main",n)
                if not a then break end
                local pat=table.concat{k," (%d+)"}
                local s=a:match(pat)
                s=tonumber(s)
                if s then
                    i=i+s
                end
            end
            if i>0 then
                insert[rom.ls](("%s %s"):format(k,i))
            end
        end
    end
    optimize()
    sleep()
end
lol='\''

end

rbmulti_progs[rbmulti_id]()
lol='\''
